import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Banner } from '../components/banner';

export default function Home() {
  console.log("styles", styles);
  const handleOnBtnClick = () => {
    console.log("Hi banner btn");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseeur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores near by" handleOnClick={handleOnBtnClick} />
      </main>
    </div>
  )
}
